# Generated by Django 5.1.3 on 2024-11-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('servingSize', models.DecimalField(decimal_places=2, max_digits=5)),
                ('servingUnits', models.CharField(max_length=50)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numberOfServings', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
