# Generated by Django 5.1.3 on 2024-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='servingSize',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='servingUnits',
            field=models.CharField(default='', max_length=50),
        ),
    ]
